user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log notice;
pid /var/run/nginx.pid;


events {
  worker_connections 1024;
}


http {
  include /etc/nginx/mime.types;
  default_type application/octet-stream;

  log_format main '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"';

  access_log /var/log/nginx/access.log main;

  sendfile on;
  #tcp_nopush     on;

  keepalive_timeout 65;

  # Compression
  gzip on;
  gzip_comp_level 2;
  gzip_types text/plain text/css application/json model/gltf+json;

  limit_req_zone $binary_remote_addr zone=req_limit_per_ip:50m rate=10r/s;
  limit_conn_zone $binary_remote_addr zone=conn_limit_per_ip:10m;

  ## Limit connections per ip
  limit_conn conn_limit_per_ip 100;
  limit_conn_status 429;

  # Prevent buffer overflow
  client_max_body_size 100k;
  large_client_header_buffers 2 1k;

  server {
    listen 80;
    server_name localhost;

    location = /health {
      access_log off;
      return 200;
    }
  }

  server {
    listen 8080;
    server_name localhost;

    location / {
      client_max_body_size 50m;
      limit_req zone=req_limit_per_ip burst=50 nodelay;
      limit_conn conn_limit_per_ip 50;

      proxy_pass http://wagtail:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Forwarded-Host $host:$server_port;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /image-auth/ {
      internal;

      limit_req zone=req_limit_per_ip burst=100 nodelay;

      proxy_pass_request_body off;
      proxy_set_header Content-Length "";
      proxy_pass http://wagtail:8000/image-auth/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Original-URI $request_uri;
    }

    location /static/ {
      add_header Cache-Control "public, max-age=7200";
      alias /usr/share/nginx/html/static/;
    }

    location /media/ {
      auth_request /image-auth/;
      proxy_pass http://wagtail:8000/media/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      add_header Cache-Control "public, max-age=7200";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
      root /usr/share/nginx/html;
    }
  }
}
