# Generated by Django 6.0.2 on 2026-09-28 19:54

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("wagtailcore", "0096_referenceindex_referenceindex_source_object_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                ("ingredients", wagtail.fields.RichTextField(blank=True)),
                ("preparation", wagtail.fields.RichTextField(blank=True)),
                (
                    "preparation_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Preparation time in minutes", null=True
                    ),
                ),
                (
                    "cooking_time",
                    models.PositiveIntegerField(
                        blank=True, help_text="Cooking time in minutes", null=True
                    ),
                ),
                (
                    "number_of_people",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("wagtailcore.page",),
        ),
    ]
